// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  article: dynamic(() => import("./Article")),
  article_part: dynamic(() => import("./ArticlePart")),
  formulaire: dynamic(() => import("./Formulaire")),
  rich_text: dynamic(() => import("./RichText")),
  text_image: dynamic(() => import("./TextImage")),
};
